from enum import Enum

class ErrorCode(str, Enum):
    # General
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    
    # User
    USER_NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_DUPLICATED = "EMAIL_DUPLICATED"
    USERNAME_DUPLICATED = "USERNAME_DUPLICATED"
    INVALID_PASSWORD = "INVALID_PASSWORD"
    EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND"
    
    # Trip
    TRIP_NOT_FOUND = "TRIP_NOT_FOUND"
    TRIP_ALREADY_EXISTS = "TRIP_ALREADY_EXISTS"
    INVALID_DATE = "INVALID_DATE"
    
    # Location
    COUNTRY_NOT_FOUND = "COUNTRY_NOT_FOUND"
    COUNTRY_ALREADY_EXISTS = "COUNTRY_ALREADY_EXISTS"
    CITY_NOT_FOUND = "CITY_NOT_FOUND"
    CITY_ALREADY_EXISTS = "CITY_ALREADY_EXISTS"
    
    # Comment
    COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND"
    COMMENT_TOO_SHORT = "COMMENT_TOO_SHORT"
    COMMENT_TOO_LONG = "COMMENT_TOO_LONG"
